[phases.setup]
nixPkgs = ["python310", "pip"]

[phases.install]
cmds = ["cd backend && pip install -r requirements.txt"]

[phases.build]
cmds = ["cd backend && python create_tables.py"]

[start]
cmd = "cd backend && python start_production.py"
